//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetTheFoodAlready.Ui.Wpf.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GetTheFoodAlready.Ui.Wpf.Resources.AppLabels", typeof(AppLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected delivery time.
        /// </summary>
        internal static string DeliveryPriceLabel {
            get {
                return ResourceManager.GetString("DeliveryPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected delivery length.
        /// </summary>
        internal static string DeliveryTimeLabel {
            get {
                return ResourceManager.GetString("DeliveryTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to vendor page.
        /// </summary>
        internal static string GoToVendorPage {
            get {
                return ResourceManager.GetString("GoToVendorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is delivery free?.
        /// </summary>
        internal static string IsDeliveryFreeLabel {
            get {
                return ResourceManager.GetString("IsDeliveryFreeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET THE FOOD ALREADY, DUDE!.
        /// </summary>
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum order.
        /// </summary>
        internal static string MinimumOrderAmountLabel {
            get {
                return ResourceManager.GetString("MinimumOrderAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REROLL!!.
        /// </summary>
        internal static string RerollButtonLabel {
            get {
                return ResourceManager.GetString("RerollButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full menu / random proposition.
        /// </summary>
        internal static string SwitchListButtonLabel {
            get {
                return ResourceManager.GetString("SwitchListButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor name.
        /// </summary>
        internal static string VendorNameLabel {
            get {
                return ResourceManager.GetString("VendorNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string VendorPointScoreLabel {
            get {
                return ResourceManager.GetString("VendorPointScoreLabel", resourceCulture);
            }
        }
    }
}
