//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetTheFoodAlready.Ui.Wpf.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PreparationWizardLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PreparationWizardLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GetTheFoodAlready.Ui.Wpf.Resources.PreparationWizardLabels", typeof(PreparationWizardLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less then {0} minutes.
        /// </summary>
        internal static string AccaptableDeliveryTimeOptionLabel {
            get {
                return ResourceManager.GetString("AccaptableDeliveryTimeOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BackButtonLabel {
            get {
                return ResourceManager.GetString("BackButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string BusyIndicatorContent {
            get {
                return ResourceManager.GetString("BusyIndicatorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CancelButtonLabel {
            get {
                return ResourceManager.GetString("CancelButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burgers.
        /// </summary>
        internal static string CuisineTypeLabelBurger {
            get {
                return ResourceManager.GetString("CuisineTypeLabelBurger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indian.
        /// </summary>
        internal static string CuisineTypeLabelIndian {
            get {
                return ResourceManager.GetString("CuisineTypeLabelIndian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string FinishButoonLabel {
            get {
                return ResourceManager.GetString("FinishButoonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check vendors for minimum order amount?.
        /// </summary>
        internal static string IsCheckingMinimumOrderAmountLabel {
            get {
                return ResourceManager.GetString("IsCheckingMinimumOrderAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select only out of labeled with &apos;free delivery&apos;?.
        /// </summary>
        internal static string IsOnlyFreeDelieryLabel {
            get {
                return ResourceManager.GetString("IsOnlyFreeDelieryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is rating of vendor point of importance?.
        /// </summary>
        internal static string IsRatingImportant {
            get {
                return ResourceManager.GetString("IsRatingImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desserts.
        /// </summary>
        internal static string MenuPartLabelDessert {
            get {
                return ResourceManager.GetString("MenuPartLabelDessert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinks.
        /// </summary>
        internal static string MenuPartLabelDrinks {
            get {
                return ResourceManager.GetString("MenuPartLabelDrinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snacks.
        /// </summary>
        internal static string MenuPartLabelSnacks {
            get {
                return ResourceManager.GetString("MenuPartLabelSnacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select minimum order amount ({0}).
        /// </summary>
        internal static string MinimunOrderAmountLabel {
            get {
                return ResourceManager.GetString("MinimunOrderAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select minimum amount of votes for rating ({0}).
        /// </summary>
        internal static string MinimunRateVoteCountLabel {
            get {
                return ResourceManager.GetString("MinimunRateVoteCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select minimum allowed rating ({0}).
        /// </summary>
        internal static string MinimunRatingLabel {
            get {
                return ResourceManager.GetString("MinimunRatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextButtonLabel {
            get {
                return ResourceManager.GetString("NextButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android-pay.
        /// </summary>
        internal static string PaymentTypeLabelAndroidPay {
            get {
                return ResourceManager.GetString("PaymentTypeLabelAndroidPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple-pay.
        /// </summary>
        internal static string PaymentTypeLabelApplePay {
            get {
                return ResourceManager.GetString("PaymentTypeLabelApplePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online by card.
        /// </summary>
        internal static string PaymentTypeLabelCardOnline {
            get {
                return ResourceManager.GetString("PaymentTypeLabelCardOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To courier by card.
        /// </summary>
        internal static string PaymentTypeLabelCourierCard {
            get {
                return ResourceManager.GetString("PaymentTypeLabelCourierCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samsung-pay.
        /// </summary>
        internal static string PaymentTypeLabelSamsungPay {
            get {
                return ResourceManager.GetString("PaymentTypeLabelSamsungPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sberbank-Spasibo.
        /// </summary>
        internal static string PaymentTypeLabelSberbankSpasibo {
            get {
                return ResourceManager.GetString("PaymentTypeLabelSberbankSpasibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose preferred cuisine types (empty means any allowed).
        /// </summary>
        internal static string SelectCuisinesLabel {
            get {
                return ResourceManager.GetString("SelectCuisinesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose preferred time-range for delivery.
        /// </summary>
        internal static string SelectDeliveryTimeTilLabel {
            get {
                return ResourceManager.GetString("SelectDeliveryTimeTilLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your location.
        /// </summary>
        internal static string SelectLocationLabel {
            get {
                return ResourceManager.GetString("SelectLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose excluded menu parts (empty means any allowed).
        /// </summary>
        internal static string SelectMenuPartsToExcludeLabel {
            get {
                return ResourceManager.GetString("SelectMenuPartsToExcludeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose preferred payment types (empty means any allowed).
        /// </summary>
        internal static string SelectPaymentTypeLabel {
            get {
                return ResourceManager.GetString("SelectPaymentTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your food preferences.
        /// </summary>
        internal static string SetupFoodPageTitle {
            get {
                return ResourceManager.GetString("SetupFoodPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Wizard will walk you though setting up food randomizer please go through all step..
        /// </summary>
        internal static string SetupLocationPageDescription {
            get {
                return ResourceManager.GetString("SetupLocationPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your location.
        /// </summary>
        internal static string SetupLocationPageTitle {
            get {
                return ResourceManager.GetString("SetupLocationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your vendor point preferences.
        /// </summary>
        internal static string SetupVendorPageTitle {
            get {
                return ResourceManager.GetString("SetupVendorPageTitle", resourceCulture);
            }
        }
    }
}
