//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetTheFoodAlready.DeliveryClubBridge.Tests.Support {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GetTheFoodAlready.DeliveryClubBridge.Tests.Support.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {
        ///	&quot;products&quot;: [
        ///		{
        ///			&quot;name&quot;: &quot;someName&quot;,
        ///			&quot;description&quot;: &quot;item description&quot;,
        ///			&quot;id&quot;: { &quot;primary&quot;: 34651436 },
        ///			&quot;price&quot;: { &quot;value&quot;: 3432 },
        ///			&quot;properties&quot;: {
        ///				&quot;volume&quot;: 435314
        ///			}
        ///		}
        ///	],
        ///	&quot;menu&quot;: [
        ///		{
        ///			&quot;name&quot;: &quot;menuItem&quot;,
        ///			&quot;productIds&quot;: [34651436]
        ///		}
        ///	]
        ///}.
        /// </summary>
        internal static string FoodInfoRespForTest {
            get {
                return ResourceManager.GetString("FoodInfoRespForTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {
        ///	&quot;vendors&quot;: {
        ///		&quot;count&quot;: 200,
        ///		&quot;hasMore&quot;: true,
        ///		&quot;items&quot;: [
        ///			{
        ///				&quot;alias&quot;: &quot;testAlias&quot;,
        ///				&quot;allowPreorder&quot;: true,
        ///				&quot;categoryId&quot;: 1,
        ///				&quot;chain&quot;: {
        ///					&quot;alias&quot;: &quot;test_msk&quot;,
        ///					&quot;id&quot;: {
        ///						&quot;primary&quot;: &quot;12345&quot;
        ///					}
        ///				},
        ///				&quot;cover&quot;: {
        ///					&quot;1200&quot;: &quot;/naturmort/5d934899ddab7_720x450.jpg&quot;,
        ///					&quot;1600&quot;: &quot;/naturmort/5d934899ddab7_720x450.jpg&quot;,
        ///					&quot;2048&quot;: &quot;/naturmort/5d934899ddab7_720x450.jpg&quot;,
        ///					&quot;480&quot;: &quot;/naturmort/5d934899ddab7_480x300.jpg&quot;,
        ///					&quot;720&quot;: &quot;/naturmort/5d9348 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string GetDeliveryClubVendorsNearbyRespForTest {
            get {
                return ResourceManager.GetString("GetDeliveryClubVendorsNearbyRespForTest", resourceCulture);
            }
        }
    }
}
